# ~/.config/starship.toml — minimal, cleaner spacing
add_newline = false
# dir → branch → prompt
format = "$directory$git_branch $character "

[directory]
truncation_length = 3
truncate_to_repo = true
# default style; no trailing spaces


[git_branch]
symbol = " "
format = " $symbol$branch" # single leading space, no trailing space


[character]
success_symbol = "❯ "
error_symbol = "❯ "